version: 1
validation: sovereign

# ✅ BUILD CONFIGURATION FOR NEXELRA
build:
  proto:
    path: proto
    third_party_paths:
      - third_party/proto
      - proto_vendor
  binary: "Nexelrad"
  main: "./cmd/Nexelrad"

accounts:
- name: alice
  coins:
  - 20000token
  - 200000000stake
- name: bob
  coins:
  - 10000token
  - 100000000stake
- name: nexelra
  coins:
  - 500000token
  - 500000000stake
- name: developer
  coins:
  - 100000token
  - 300000000stake

client:
  openapi:
    path: docs/static/openapi.yml

faucet:
  name: nexelra
  coins:
  - 10token
  - 200000stake

validators:
- name: alice
  bonded: 100000000stake
- name: validator1
  bonded: 150000000stake
- name: validator2
  bonded: 200000000stake
- name: validator3
  bonded: 300000000stake
- name: nexelra-validator
  bonded: 400000000stake

# ✅ GENESIS CONFIGURATION
genesis:
  chain_id: nexelra
  
# ✅ NETWORK HOST CONFIGURATION
host:
  rpc: :26657
  p2p: :26656
  prof: :6060
  grpc: :9090
  grpc-web: :9091
  api: :1317

# ✅ SNAPSHOT & OPTIMIZATION CONFIGURATION
init:
  config:
    consensus:
      timeout_commit: "1s"
      timeout_propose: "3s"
      timeout_prevote: "1s"
      timeout_precommit: "1s"
      skip_timeout_commit: false
    app:
      # Snapshot Configuration
      snapshot-interval: 100      # Take snapshot every 100 blocks
      snapshot-keep-recent: 5     # Keep 5 most recent snapshots
      snapshot-dir: "data/snapshots"
      
      # Pruning Configuration
      pruning: "custom"
      pruning-keep-recent: "100"
      pruning-interval: "10"
      min-retain-blocks: 0
      
      # Indexing Configuration
      index-events: 
        - "tx.height"
        - "tx.hash"
        - "message.sender"
        - "message.action"
        - "transfer.recipient"
        - "transfer.sender"
        - "identity.verified"
        - "identity.created"
      
      # Performance Optimizations
      minimum-gas-prices: "0.001stake"
      halt-height: 0
      halt-time: 0
      inter-block-cache: true
      
      # API Configuration
      api:
        enable: true
        swagger: true
        enabled-unsafe-cors: true
        max-open-connections: 1000
        rpc-read-timeout: 10
        rpc-write-timeout: 10
        rpc-max-body-bytes: 1000000
        
      # gRPC Configuration  
      grpc:
        enable: true
        address: "0.0.0.0:9090"
        max-recv-msg-size: "10485760"
        max-send-msg-size: "2147483647"
        
      # State Sync Configuration
      state-sync:
        snapshot-interval: 100
        snapshot-keep-recent: 5
        
      # Memory & Performance
      iavl-cache-size: 781250
      iavl-disable-fastnode: false
      
      # Telemetry
      telemetry:
        service-name: "nexelra"
        enabled: false
        enable-hostname: false
        enable-hostname-label: false
        enable-service-label: true
        prometheus-retention-time: 60
        global-labels: []

# ✅ DEVELOPMENT & TESTING CONFIGURATION
dev:
  # Auto-restart on file changes
  watch: true
  
  # Custom modules to watch
  watch_paths:
    - "x/"
    - "app/"
    - "cmd/"
    
  # Reset data on restart
  reset_once: false
  
  # Custom flags for development
  flags:
    - "--log_level=debug"
    - "--trace"

# ✅ DEPLOYMENT CONFIGURATION
deployment:
  # Docker configuration
  docker:
    enabled: true
    image: "nexelra/node"
    tag: "latest"
    
  # Kubernetes configuration  
  kubernetes:
    enabled: false
    namespace: "nexelra"
    replicas: 3
    
# ✅ IDENTITY MODULE SPECIFIC CONFIG
identity:
  verification:
    required: true
    auto_approve: false
    admin_approval: true
  
  kyc:
    enabled: true
    levels: ["basic", "intermediate", "advanced"]
    
# ✅ MONITORING & LOGGING
monitoring:
  prometheus:
    enabled: true
    port: 26660
    
  logging:
    level: "info"
    format: "json"
    output: "stdout"
    
# ✅ SECURITY CONFIGURATION  
security:
  cors:
    allowed_origins: ["*"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed_headers: ["*"]
    
  rate_limiting:
    enabled: true
    requests_per_second: 100
    burst: 200